# JDBC URL ???????????
url=jdbc:postgresql://localhost:5433/postgres

# ????? ? ?????? ???? ??????
username=postgres
password=test

# ??? ???????? ???? ??????
driver=org.postgresql.Driver

# ???? ? ?????????? (changelog)
changeLogFile=migrations/master.xml

# ???????????
logLevel=info
